backend:
  # Choose the backend you prefer (GitHub, GitLab, BitBucket)
  # Reference: https://www.netlifycms.org/docs/authentication-backends/
  name: github
  branch: master
  repo: bluecollardev/clients-wilderwind

media_folder: "static/images"
public_folder: "static/images"

collections:
  - name: "data"
    label: "Pages"
    files:
      - name: "services"
        label: "Services"
        file: "src/data/Services.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Services" }
          - { label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false }
          - { label: "Meta Description", name: "metaDescription", widget: "text", required: false }
          - name: "services"
            label: "List Services"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false }
              - { label: "Meta Description", name: "metaDescription", widget: "text", required: false }
              - { label: "Summary", name: "summary", widget: "text", required: false }
              - { label: "Description", name: "description", widget: "markdown", required: false }
              - { label: "Image", name: "image", widget: "string", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }
              - { label: "Link Text", name: "linkText", widget: "string", required: false }
              - { label: "Caption", name: "caption", widget: "string", required: false }
              - { label: "Sub-Caption", name: "subCaption", widget: "string", required: false }

  - name: "site"
    label: "Site"
    files:
      - name: "contact"
        label: "Contact"
        file: "src/data/Contact.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Contact" }
          - { label: "Meta Keywords", name: "metaKeywords", widget: "string", required: false }
          - { label: "Meta Description", name: "metaDescription", widget: "text", required: false }
          - { label: "Summary", name: "summary", widget: "text" }
          - { label: "Description", name: "description", widget: "markdown" }

      - name: "socialmedia"
        label: "Social Media"
        file: "src/data/SocialMedia.yml"
        fields:
          - { label: "Title", name: "title", widget: "string", default: "Social Media" }
          - name: "items"
            label: "Social Media"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

